export const PACKAGE_JSON_READ = 'PACKAGE_JSON_READ'
export const PACKAGE_JSON_READ_ERROR = 'PACKAGE_JSON_READ_ERROR'
export const GIT_OPEN_SUCCESS = 'GIT_OPEN_SUCCESS'
export const GIT_OPEN_ERROR = 'GIT_OPEN_ERROR'
