
export const UPDATE_FILE_TREE = 'FILES_WINDOW/UPDATE_FILE_TREE'
export const FILE_TREE_UPDATED = 'FILES_WINDOW/FILE_TREE_UPDATED'
export const SAVE_FILE = 'FILES_WINDOW/SAVE_FILE'
export const SAVE_FILE_SUCCESS = 'FILES_WINDOW/SAVE_FILE_SUCCESS'
