
export const START = 'TASK_START'
export const MESSAGE = 'TASK_RUN_MESSAGE'
export const ERROR_MESSAGE = 'TASK_RUN_ERROR_MESSAGE'
export const END_WITH_CODE = 'TASK_END_WITH_CODE'

export const NPM_INSTALL_START = 'NPM_INSTALL_START'
export const NPM_INSTALL_MESSAGE = 'NPM_INSTALL_MESSAGE'
export const NPM_INSTALL_END = 'NPM_INSTALL_END'
export const NPM_INSTALL_ERROR_MESSAGE = 'NPM_INSTALL_ERROR_MESSAGE'
