export const SELECT_TAB = 'CONTEXT_SWITCHER_SELECT_TAB';

export const TASKS = 'CONTEXT_SWITCHER_KEY_TASKS';
export const FILES = 'CONTEXT_SWITCHER_KEY_FILES';
export const GIT = 'CONTEXT_SWITCHER_KEY_GIT';
